services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis
    ports:
      - 6379:6379

  # app:
  #   build: .
  #   ports:
  #     - 3000:3000
  #   env_file: .env
  #   depends_on:
  #     - mysql
  #     - redis
