import { readFileSync } from "node:fs";
import { NestFactory } from "@nestjs/core";
import { DocumentBuilder, SwaggerModule } from "@nestjs/swagger";
import * as swaggerUi from "swagger-ui-express";
import { AppModule } from "./app.module";
import metadata from "./metadata"; // <-- file auto-generated by the "PluginMetadataGenerator"

async function bootstrap() {
	const app = await NestFactory.create(AppModule);
	app.enableShutdownHooks();
	app.setGlobalPrefix("api");

	// Explicitly defined API
	await SwaggerModule.loadPluginMetadata(metadata);
	const config = new DocumentBuilder()
		.setTitle("Explicitly defined API")
		.setDescription("OpenAPI Documentation for explicitly defined API")
		.setVersion("1.0")
		.addBearerAuth()
		.build();
	const nestDocument = SwaggerModule.createDocument(app, config);

	// Auto generated API
	const generatedOpenApiDocument = JSON.parse(
		readFileSync("openapi.json", "utf8"),
	);

	SwaggerModule.setup("/api-docs/nest", app, nestDocument);
	SwaggerModule.setup("/api-docs/generated", app, generatedOpenApiDocument);

	const swaggerUiOptions: swaggerUi.SwaggerOptions = {
		explorer: true,
		swaggerOptions: {
			urls: [
				{ url: "/api-docs/nest-json", name: "Explicitly defined API" },
				{ url: "/api-docs/generated-json", name: "Auto generated API" },
			],
		},
	};

	app.use(
		"/api-docs",
		swaggerUi.serve,
		swaggerUi.setup(null, swaggerUiOptions),
	);

	await app.listen(3000);
}
bootstrap();
