import { readFileSync } from "node:fs";
import { NestFactory } from "@nestjs/core";
import { DocumentBuilder, SwaggerModule } from "@nestjs/swagger";
import { enhance } from "@zenstackhq/runtime";
import { ZenStackMiddleware } from "@zenstackhq/server/express";
import * as swaggerUi from "swagger-ui-express";
import { AppModule } from "./app.module";
import { PrismaService } from "./prisma.service";

import metadata from "./metadata"; // <-- file auto-generated by the "PluginMetadataGenerator"

async function bootstrap() {
	const app = await NestFactory.create(AppModule);
	app.setGlobalPrefix("api");

	// Explicitly defined API
	await SwaggerModule.loadPluginMetadata(metadata);
	const nestDocument = SwaggerModule.createDocument(app, {
		info: {
			title: "Explicitly defined API",
			description: "OpenAPI Documentation for explicitly defined API",
			version: "1.0",
		},
		openapi: "3.1.0",
	});

	// Auto generated API
	const generatedOpenApiDocument = JSON.parse(
		readFileSync("openapi.json", "utf8"),
	);

	SwaggerModule.setup("/api-docs/nest", app, nestDocument);
	SwaggerModule.setup("/api-docs/generated", app, generatedOpenApiDocument);

	const swaggerUiOptions: swaggerUi.SwaggerOptions = {
		explorer: true,
		swaggerOptions: {
			urls: [
				{
					url: "/api-docs/nest-json",
					name: "Explicitly defined API",
				},
				{
					url: "/api-docs/generated-json",
					name: "Auto generated API",
				},
			],
		},
	};

	app.use(
		"/api-docs",
		swaggerUi.serve,
		swaggerUi.setup(null, swaggerUiOptions),
	);

	const prisma = app.get(PrismaService);

	app.use(
		"/models",
		ZenStackMiddleware({
			getPrisma: (req) => enhance(prisma, { user: { id: "1" } }),
		}),
	);

	await app.listen(3000);
}
bootstrap();
