import { readFileSync } from "node:fs";
import { NestFactory } from "@nestjs/core";
import { DocumentBuilder, SwaggerModule } from "@nestjs/swagger";
import { AppModule } from "./app.module";
import metadata from "./metadata"; // <-- file auto-generated by the "PluginMetadataGenerator"
import { apiReference } from "@scalar/nestjs-api-reference";
import { Request, Response } from "express";

async function bootstrap() {
	const app = await NestFactory.create(AppModule);
	app.enableCors();
	app.enableShutdownHooks();
	app.setGlobalPrefix("api");

	// Explicitly defined API
	await SwaggerModule.loadPluginMetadata(metadata);
	const config = new DocumentBuilder()
		.setTitle("Explicitly defined API")
		.setDescription("OpenAPI Documentation for explicitly defined API")
		.setVersion("1.0")
		.addBearerAuth()
		.build();
	const nestDocument = SwaggerModule.createDocument(app, config);

	// Auto generated API
	const generatedOpenApiDocument = JSON.parse(
		readFileSync("openapi.json", "utf8"),
	);

	app.use("/api-docs", apiReference({ spec: { content: nestDocument } }));
	app.use("/api-docs-json", (_: Request, res: Response) => {
		res.json(nestDocument);
	});

	app.use(
		"/reference",
		apiReference({ spec: { content: generatedOpenApiDocument } }),
	);

	await app.listen(process.env.PORT || 3000);
}
bootstrap();
